### ISSUE TITLE
Needing help getting a UDF Filesystem Driver to work

### ISSUE THREAD

**Issue by Zero3K** [williamdevries/UDF#2]
I am having a guy work on it. Right now, he is stuck on getting it to recognize the AVDP that Windows 7/10/Linux includes when formatting a Hard Disk as it. The driver's source code is at https://github.com/reactos/reactos/tree/master/drivers/filesystems/udfs.

**Comment by Zero3K** [comment]
I have found another developer to help him get it working, etc.

**Comment by Zero3K** [comment]
Please answer the questions that he commented to this issue:

https://github.com/Zero3K/udfs/issues/1

**Comment by williamdevries** [comment]
This isn't related to this repo.
